import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen w-screen flex-col py-2">
        <h1 className="text-4xl">blog</h1>
        <OgImage>
          <Blog date="June 1, 2021" title="Lorem ipsum dolor sit" length={5} />
        </OgImage>
        <OgImage>
          <Blog
            date="June 1, 2021"
            title="Lorem ipsum dolor sit amet consetetur sadipscing elitr"
            length={5}
          />
        </OgImage>
        <h1 className="text-4xl">another thing</h1>
      </div>
    </>
  );
};

function OgImage(props: { children: React.ReactNode }) {
  return (
    <div className="flex h-[700px] w-[1260px] flex-col items-center justify-center">
      <div className="flex h-[630px] w-[1200px] flex-col items-center justify-center">
        {props.children}
      </div>
    </div>
  );
}

function Blog(props: {
  date: string;
  title: string;
  length: number;
  isVideo?: boolean;
}) {
  return (
    <div className="flex h-full w-full flex-col overflow-clip bg-[hsl(15,35%,5%)] bg-cover p-16 text-[hsl(15,15%,90%)]">
      <div className="sticky right-10 top-0 z-0 h-4 w-4 rounded-full bg-transparent shadow-[820px_420px_600px_600px_rgba(255,100,100,0.12)]" />
      <div className="z-100 flex h-full w-full flex-col justify-between">
        <div className="flex flex-col gap-16">
          <div className="flex justify-between">
            <img
              className="z-4"
              src="https://www.c-ehrlich.dev/_astro/avatar.aa3e3aeb_Z1JGnRO.jpg"
              width="160px"
              height="160px"
              alt="Christopher Ehrlich Avatar"
            />
            {/* <p className="text-4xl">c-ehrlich.dev</p> */}
            <p className="text-4xl">Christopher Ehrlich</p>
            {/* <p className="text-4xl">c-ehrlich.dev</p> */}
          </div>
          <h1 className="my-0 py-0 text-7xl font-extrabold leading-tight">
            {props.title}
          </h1>
        </div>
        <div className="flex justify-between text-4xl">
          <p className="text-orange-300/90">
            {props.length} minute {props.isVideo ? "video" : "read"}
          </p>
        </div>
      </div>
    </div>
  );
}

export default Home;
