import { type NextPage } from "next";
import Head from "next/head";
import "@fontsource/inter";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          minHeight: "100vh",
          width: "100vw",
          flexDirection: "column",
          padding: "2rem",
        }}
      >
        <h1 style={{ fontSize: "36px" }}>site</h1>
        <OgImage>
          <Site />
        </OgImage>
        <h1 style={{ fontSize: "36px" }}>blog</h1>
        <OgImage>
          <Blog
            title="Lorem ipsum dolor sit amet consetetur sadipscing elitr"
            minRead={5}
          />
        </OgImage>
      </div>
    </>
  );
};

function OgImage(props: { children: React.ReactNode }) {
  return (
    <div
      style={{
        margin: "64px",
        display: "flex",
        height: "630px",
        width: "1200px",
        flexDirection: "column",
        overflow: "hidden",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      {props.children}
    </div>
  );
}

function Site() {
  return (
    <div
      style={{
        display: "flex",
        height: "630px",
        width: "1200px",
        flexDirection: "column",
        overflow: "hidden",
        fontFamily: "Inter",
        backgroundColor: "hsl(15,35%,5%)",
        color: "hsl(15,15%,90%)",
        padding: "64px",
      }}
    >
      <div style={{ display: "flex", position: "absolute" }}>
        <div
          style={{
            display: "flex",
            position: "relative",
            zIndex: "0",
            height: "16px",
            width: "16px",
            borderRadius: "50%",
            backgroundColor: "transparent",
            boxShadow: "1030px 600px 800px 800px rgba(255,140,100,0.12)",
          }}
        />
      </div>
      <div
        style={{
          zIndex: "100",
          display: "flex",
          flexDirection: "column",
          gap: "64px",
          alignItems: "center",
          justifyContent: "center",
          height: "100%",
          width: "100%",
        }}
      >
        <img
          style={{
            zIndex: "4",
            borderRadius: "50%",
          }}
          src="https://www.c-ehrlich.dev/og/avatar.jpg"
          width="224px"
          height="224px"
          alt="Christopher Ehrlich Avatar"
        />
        <h1
          style={{
            marginBottom: "16px",
            fontSize: "72px",
            fontWeight: "700",
          }}
        >
          Christopher Ehrlich
        </h1>
      </div>
    </div>
  );
}

function Blog(props: { title: string; minRead: number; isVideo?: boolean }) {
  return (
    <div
      style={{
        display: "flex",
        height: "630px",
        width: "1200px",
        flexDirection: "column",
        overflow: "hidden",
        backgroundColor: "hsl(15,35%,5%)",
        backgroundSize: "cover",
        padding: "64px",
        color: "hsl(15,15%,90%)",
        fontFamily: "Inter",
        boxSizing: "border-box",
      }}
    >
      <div
        style={{
          display: "flex",
          position: "absolute",
          border: "1px solid white",
        }}
      >
        <div
          style={{
            display: "flex",
            position: "relative",
            zIndex: "100",
            height: "16px",
            width: "16px",
            borderRadius: "50%",
            border: "1px solid green",
            backgroundColor: "red",
            boxShadow: "1030px 600px 800px 800px rgba(255,140,100,0.12)",
          }}
        />
      </div>
      <div
        style={{
          zIndex: 100,
          display: "flex",
          flexDirection: "column",
          border: "1px solid yellow",
          justifyContent: "space-between",
          height: "100%",
          width: "100%",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            border: "1px solid orange",
            gap: "64px",
            width: "100%",
            margin: "0px",
            padding: "0px",
          }}
        >
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              width: "100%",
              border: "1px solid red",
              alignItems: "flex-start",
            }}
          >
            <img
              style={{ zIndex: "4", borderRadius: "50%" }}
              src="https://www.c-ehrlich.dev/og/avatar.jpg"
              width="160px"
              height="160px"
              alt="Christopher Ehrlich Avatar"
            />
            <p
              style={{
                fontSize: "36px",
                verticalAlign: "top",
                marginTop: "-4px",
              }}
            >
              Christopher Ehrlich
            </p>
          </div>
          <h1
            style={{
              margin: "0px",
              padding: "0px",
              fontSize: "72px",
              lineHeight: "90px",
              fontWeight: "800",
              border: "1px solid blue",
            }}
          >
            {props.title}
          </h1>
        </div>
        <p
          style={{
            border: "1px solid green",
            fontSize: "36px",
            margin: "0",
            padding: "0",
            color: "rgb(253 186 116 / 0.9)",
          }}
        >
          {props.minRead} minute {props.isVideo ? "video" : "read"}
        </p>
      </div>
    </div>
  );
}

export default Home;
