import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen w-screen flex-col py-2">
        <h1 className="text-4xl">blog</h1>
        <OgImage>
          <Blog
            date="June 1, 2021"
            title=" Writing clean React Query code in a world where most of it is not so clean"
          />
        </OgImage>
        <h1 className="text-4xl">another thing</h1>
      </div>
    </>
  );
};

function OgImage(props: { children: React.ReactNode }) {
  return (
    <div className="flex h-[700px] w-[1260px] flex-col items-center justify-center">
      <div className="flex h-[630px] w-[1200px] flex-col items-center justify-center">
        {props.children}
      </div>
    </div>
  );
}

function Blog(props: { date: string; title: string }) {
  return (
    <div className="flex h-full w-full flex-col bg-[hsl(15,35%,5%)] bg-cover p-16 text-[hsl(15,15%,90%)]">
      <div className="gap- flex h-full w-full flex-col justify-between">
        <div className="flex flex-col gap-8">
          <img
            className="rounded-full"
            src="https://www.c-ehrlich.dev/assets/avatar.3ca5b4ed_aYQcn.jpg"
            width="196px"
            height="196px"
            alt="Christopher Ehrlich Avatar"
          />
          <h1 className="my-0 py-0 text-6xl font-extrabold leading-tight">
            {props.title}
          </h1>
        </div>
        <p className="text-4xl">c-ehrlich.dev</p>
      </div>
    </div>
  );
}

export default Home;
